<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>AltyaziDB.Player.Telegram</RootNamespace>
    <AssemblyName>ADB.Player.Telegram</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AltyaziDB.Player.Core\AltyaziDB.Player.Core.csproj" />
    <PackageReference Include="tdlib.native.win-x64" />
    <PackageReference Include="SharpCompress" />
  </ItemGroup>
</Project>
