<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AltyaziDB.Player.Sources</RootNamespace>
    <AssemblyName>ADB.Player.Sources</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AltyaziDB.Player.Core\AltyaziDB.Player.Core.csproj" />
  </ItemGroup>
</Project>
